version: '3.8'
services:
  mysql-container-2:
    image: mysql:8.0
    container_name: mysql-container-2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project
    ports:
      - "3309:3306"

  spring-boot-app:
    image: ronodennis/spring-api-docker:1.9
    container_name: spring-boot-app
    environment:
      MYSQL_HOST: mysql-container-2
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "8086:8086"
    depends_on:
      - mysql-container-2

networks:
  default:
    driver: bridge




#version: '3.8'
#services:
#  mysql-container-2:
#    image: mysql:8.0
#    container_name: mysql-container-2
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: project
#    ports:
#      - "3309:3306"
#    networks:
#      - springboot-mysql-network
#
#  spring-boot-app:
#    image: ronodennis/spring-api-docker:1.3
#    container_name: spring-boot-app
#    environment:
#      MYSQL_HOST: mysql-container-2
#      MYSQL_PORT: 3306
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
#    ports:
#      - "8086:8086"
#    depends_on:
#      - mysql-container-2
#    networks:
#      - springboot-mysql-network
#
#networks:
#  springboot-mysql-network:
#    driver: bridge
